# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/tale"
url:            "https://chesterhow.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Chester How
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post
  - jekyll-toc

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

# ToC
toc:
  min_level: 1
  max_level: 2
  no_toc_section_class: 'no-toc'
  list_class: 'toc-list'
  item_class: 'toc-item'
  sublist_class: 'toc-sublist'
  link_class: 'toc-link'
  toc_levels: 1..6
